### PR TITLE
Initial Resource model

### LINKED ISSUE #1: Set up a DRF /resources endpoint
Guide: https://www.django-rest-framework.org/tutorial/quickstart/

### LINKED ISSUE #6: Initial Resources model and admin form
Create the initial Resource model and register it with the Django Admin.

### PR DESCRIPTION
**Pull request by brylie**
Add the initial `Resource` model and API endpoint, as well as register it with Django Admin.

Closes #1 
Closes #6

### CODE REVIEW

**Comment by brylie** [comment]
Ping @lpatmo

**Comment by lpatmo** [comment]
@brylie Thanks so much for your PR!! I'm a little overwhelmed this week (traveling); will review as soon as I can!

**Comment by brylie** [comment]
Cool beans. Have safe and fun travels :-)

**Comment by lpatmo** [comment]
@brylie Sorry again for taking a while to review this! And thank you so much for livestreaming what you worked on at https://www.youtube.com/watch?v=cO1RRBQJw-Q!

1/ Overall looks good! :) 

2/ One thing, though -- @BethanyG pointed out that I forgot to link to https://app.swaggerhub.com/apis-docs/billglover/CodeBuddies/0.0.1 on the README. It's the API spec we're generally following for all of the prototypes. I'm not sure if it'd be easier to merge this and THEN update the models in a separate PR, or do it here in one go. Happy to do the former if it's easier!

3/ I'm running into 
```
  File "/Users/lpnotes/Desktop/django-concept/cbv3/lib/python3.7/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'resources.app'
```
... when I run `python manage.py runserver`, and blanking a little on what I should be doing to dispel that error. I checked out your branch and am in my virtualenv, and also ran a `pip install -r requirements.txt`. Will take a closer look at what you did in the livestream if I don't figure it out tomorrow. 

4/ Curious if @BethanyG has thoughts/additional comments, since I know she was working on the DRF part of this too. 

Thank you! 🙏🙏

**Comment by lpatmo** [comment]
Update: Figured out #3, heh. Needed to be `"resources.apps.ResourcesConfig",`; was missing an "s"

**Comment by brylie** [comment]
Lets consider merging this request, and then taking a second attempt to align with the specification.

**Comment by lpatmo** [comment]
Thanks @brylie! Sorry again about forgetting to link to the API specs.

**Pull request closed without merging**
