### PR TITLE
Issue 160 hangouts endpoint first pass

### LINKED ISSUE #160: [TRACKING ISSUE -API] Add New Hangouts Endpoint
### This is a **Tracking Issue**, individual task issues linked:

**`working branch`:**  **`TODO:  fill in working branch here`** 

[ ]  Create JSON spec for `hangouts` api endpoint **`TODO:  fill in issue link here`** 
[ ]  Create sample data/mocked data fixture for `hangouts` api endpoint  **`TODO:  fill in issue link here`** 
[ ]  Create `hangouts` app, `apps.py` **`TODO:  fill in issue link here`** 
[ ]  Create `hangouts` model & associated DB migration files  **`TODO:  fill in issue link here`** 
[ ]  Create `hangouts` views & queries  **`TODO:  fill in issue link here`**  
[ ]  Create `hangouts` serializer  **`TODO:  fill in issue link here`** 
[ ]  Create `hangouts` admin view and register app with Django admin interface  **`TODO:  fill in issue link here`** 
[ ]  Create `hangouts` URLs  (`api\v1\projects`, and any others needed)  **`TODO:  fill in issue link here`** 
[ ]  Ensure associated unittests and test data are created for all code changes
[ ]  Document expected GET, POST, PATCH behavior and any other endpoint-specific docs 

## Acceptance Criteria:

All items checked off above, and all associated PRs reviewed, accepted, and merged.

### LINKED ISSUE #163: [API] Create Hangouts Django App and associated apps.py Files
**`PARENT TRACKING ISSUE`**: #160 

Create a Django app `hangouts` for the new  **Hangouts** api endpoint, and a `apps.py` file to go with it.

See [**Django startapp**](https://docs.djangoproject.com/en/3.0/ref/django-admin/#startapp) for some background details on how to do this via the `manage.py` app when using a `virtualenv`.  

Since we are mostly using docker, `docker-compose run --rm app django-admin startapp hangouts` is the equivalent command to create the folders and placeholders. 

You can also create the folders manually directly inside the git repo, but this won't give you the placeholder files that Django creates automatically.

### LINKED ISSUE #164: [API] Create Model for Hangouts Enpoint
**`PARENT TRACKING ISSUE`**: #160 

Based on the current proposed hangouts JSON, create a hangout model for the corresponding DB tables to support the hangouts DRF app.

JSON spec under discussion can be found in issue #161, check there for any changes/discussion.

### LINKED ISSUE #167: [API] Register Hangouts Endpoint with Admin Interface and Create Admin Views
We will want the ability to review/administer the **Hangouts** endpoint through the Django Admin interface, and so will want to register our `projects` app with the Django admin and provide any custom admin views we think we'll need.

See [**The Django Admin Site**](https://docs.djangoproject.com/en/3.0/ref/contrib/admin/#overview), [**Admin Actions**](https://docs.djangoproject.com/en/3.0/ref/contrib/admin/actions/), and [**Customizing the Admin**](https://docs.djangoproject.com/en/3.0/ref/contrib/admin/#customizing-the-adminsite-class) for more details on how to start.

See [**Resources : admin.py**](https://github.com/codebuddies/backend/blob/master/cbv3_django_prototype/cbv3_django_prototype/resources/admin.py) for an example of how the `resources` endpoint customized the Admin to display tags appropriately. 

_______
**WARNING:**  Since `hangouts` will also include a potential **manytomany** relation with **users**, there may need to be additional customization around those relations for the Admin interface.

### PR DESCRIPTION
**Pull request by BethanyG**
## What type of PR is this? (check all applicable)

**working branch:  `issue-160-hangouts-endpoint`**
**Note:** Because this code has been branched from the work in `dj-rest-auth`, the commits for PR #187 can also be seen in this PR.

- [ ] 🐛 Bug Fix
- [X] ✨ Feature (_**e.g.** API change, enhancement, addition, etc._)
- [ ] ♻️ Refactor
- [ ] 📝 Documentation
- [ ] 🔖 Release
- [ ] 🚩 Other (**concerning:**          )

## Context

"Rough Draft" of Hangouts endpoint.  Includes `app.py`, `models.py`, and `admin.py`.   See issue #160 for more detail and the inter-related issues for tracking.  See FE discussions  https://github.com/codebuddies/frontend/discussions/137 & https://github.com/codebuddies/frontend/discussions/139 for additional discussion.

## Other Related Tickets & Documents

#161, #163, #164,  #167 
 
## Implementation Details
What was your thought process as you changed the code? What does someone need to consider in reviewing it?

I left notes and questions under the related issues.  Model and JSON are far from finalized.  Additionally, this build has a somewhat "broken" admin interface -- inlines are not working there yet.  

Added a `hangouts` app
Added `hangout`, `hangoutresponses` and `hangoutsessions` tables
Added a many-to-many for resources to `hangout` and to `hangoutsessions`
Added a many-to-many for users to `hangout`, `hangoutsessions`, and `hangoutresponses`
Started to add the endpoint to the `admin`, but encountered some issues.

## New Libraries/Dependancies Introduced (Fill out as needed)

This requires a re-build and db migrations for the new tables.

## Any new migration files added?

- [ x] 👍 yes -- **0001_inital.py for initial hangouts tables creation.**
- [ ] 🙅 no, because they aren't needed

## Did you add tests?
**_Code added or changed without test coverage or good reason for exemption won't be approved._**

- [ ] 👍 yes
- [ ] 🙋 no, because I need help
- [x] 🙅 no, because they aren't needed - this is a WIP PR, and is not yet finalized to the point where test can be written

## Did you add documentation?

- [ ] 📜 readme.md
- [ ] 📜 contributing.md
- [ ] 📜 wiki entry
- [ ] 🙋 I'd like someone to help write documentation, and will file a new issue for it
- [ X] 🙅 no documentation needed -- again, this is a WIP and is not finalized yet.

### CODE REVIEW

**Comment by BethanyG** [comment]
Still open.

**Comment by BethanyG** [comment]
Keeping this open, as I hope to get to it soonish.

**Comment by BethanyG** [comment]
Still open.

**Review by e7ChatsApp — APPROVED** [review]
@BethanyG 
BethanyG:issue-160-hangouts-endpoint

**Pull request closed without merging**
