### PR TITLE
Resource tag manager

### LINKED ISSUE #16: Tagging in the DB
Pulled from a PR conversation: 

@BethanyG: 

Agreed. The classic way to model something like this would be with a many-to-many and a Tags table. This was more a quick nod to the API specs, as well as an experiment with postgres JSONB capabilities. So a bit of a hand-wave.

But as this system grows, I do have a few concerns/caveats with a "simple" many-to-many Tags table:

Tags will most likely be a freeform field on the front end. I don't really see our users choosing from an epic list of tags...and the "common convention" is for users to enter what they see fit. This means writing a bunch of code to search for already existing tags and similar tags, and only add truly new/unique tags to the DB. Even with that, the Tags table will potentially be a mess of overlapping and duplicate data from the get-go. Just mocking up 28 resources for testing data created a "mess" -- and I am only one human.

Learning Paths, Hangouts, Notes and Discussions will also be tagged, I would imagine. So there will be potentially a lot of relations tracing back to the Tags table, each having overlapping, but not necessarily identical topics....so each would have to access the code for searching for existing tags/adding new tags. With virtually everything connecting to the Tags table (and it being updated a lot per user, hangout, note, discussion, etc.), it could become a bottleneck fairly quickly.

Postgres can index JSONB, and perform many of the same queries on JSONB that it can on regular data with small syntax changes. Both autocomplete and recommendations can be done (albeit not at top speed) with documents. But yes - if we are going the RDBMS route, then we shouldn't use JSONB too often, or in too many places.

One option is to use https://github.com/jazzband/django-taggit along with https://github.com/glemmaPaul/django-taggit-serializer, and customize the code so that each model has it's tags. See this for a rundown and some thoughts: https://medium.com/sthzg/a-short-exploration-of-django-taggit-bb869ea5051f.

And all that being said, I don't like how the Tags field adds an extra level right now, so I'm going to look at re-writing the serializer to omit that, and do some more digging on how Tags are implemented in other systems to see some more options. Do you have a go-to model/resource you can share?? That would be great.

@brylie: 
We ended up using a lot of JSONB where I work, and it has been a bit of a wrestling match. The main take-away, from a senior developer colleague of mine, is to only use JSONB for specific optimizations and to default to using a relational model with Postgres.

As mentioned, we can use an auto-complete widget along with the django-taggit package to improve consistency and avoid bespoke tagging code.

----

To expand a little bit, JSONB is good to used when we need 'data locality', in effect avoiding a second query or JOIN to get a related entity.

In general, Tags are used to show related content, e.g. "resources tagged Python". I believe that it will be desirable to use these tags to create views showing similar items, resources, etc.

The performance penalty comes when we try to search within the JSONB column (even with an index) for a tag string in the name property, and then join related documents together.

For these reasons, JSONB does not seem like a good approach for tagging, particularly when the django taggit package makes a proper M2M tagging approach very straightforward.

Please excuse my directness, but I strongly recommend we use the django-taggit approach here or to omit the tagging feature from this pull request.

### LINKED ISSUE #25: UUID for Tags??
Putting this here for discussion.  As currently modeled, our Resources have a JSON field with tags that have a UUID and a text string.  We may decide to change this, but for now that is the model.  The current UUIDs are below.  Should we continue in this pattern, or should we not assign UUIDs to tags?

UUID | Tag Name
-- | --
20fba58a-2702-4378-b0f9-5ac0193d4965 | Django
32cd4ddc-6a8e-48b2-be60-45de1784e5c7 | Python
f81f08af-6bdd-465f-8aba-1693e7348f7d | REST
d4ab862d-1746-4cd3-a91a-a861e2a6c5a1 | Go
a1167632-abb8-4ce1-b090-b84e79c94c7f | JavaScript
66cc3539-6705-45ee-b15d-644d5fb90c41 | ES6
c265a4fe-d03f-445d-805f-477e05d9f4cb | Node
e7891e62-8934-486e-8085-09f557bf06f6 | HTML5
f9be333e-37c7-4eb1-9b0a-44bd782dab9f | CSS
eab9af24-7e12-440c-bf81-48a8646b6825 | LESS
7a544998-cc89-4f25-8010-be7012a615d6 | SASS
446bd3dd-2190-4747-8a43-fcb0455ae660 | Vue
c368c671-4083-4d2d-b4e7-2047a889249d | Java
8b99bcd9-a9a5-4455-b2da-fed06051d502 | React
4ddfcfff-1072-4f58-b784-02d21962f405 | GraphQL
28be75b0-35cb-4e6b-ba7c-b7ecc9b17a99 | Flask
e0dd22e2-bb8d-42e9-a69c-9e16c587182f | Ruby
8747c553-8720-4c38-8008-1f935092819a | Rails
46db9c68-70f6-4e8f-b8fc-e2cf2b347cd5 | Serverless
f9680bf4-e54b-43a9-a7a8-fe795b4ce87b | AWS
ce9d8208-cb7c-4d1e-afe9-c7cda11afffe | SQL
dde07882-276f-4539-bdcc-e9b769455b78 | Postgres
4200aed9-f773-4cee-ac5a-301dc7a646e7 | Frameworks
0d325a30-7262-4914-90fe-6c90ac725fc2 | FrontEnd
a442f459-74bf-4206-addc-432680f11c44 | Redux
e02e9635-be20-4063-9baa-46af17e33811 | .NET
48c0e583-9fed-49a1-b1a3-0f2daea4fa97 | Algorithms
cd8f53dd-baa4-43b5-a869-1fc1541c67ec | CS
7ac87ffc-051d-46f8-8f9c-cc4fd8a4df74 | Career
faf79c64-7722-4b00-84c0-a805cf3f4b16 | Interviews
3e73c86f-fadf-48fb-ae1e-6b847e3934eb | Angular
96c2e86f-af02-44fb-ba80-4480efc95324 | TypeScript
c0f3c83d-bb25-4746-ad44-0fbb9a660e17 | Podcast
ba7b7dbb-d082-4ff0-905e-522b30aaec2c | BackEnd
b864f017-91de-48f6-a02b-b903abe4ecb3 | Databases
75af4e8f-6bdf-486e-97cd-13e8d434e398 | Docker
c0142708-7ead-4bbd-b12a-7581a1056317 | Swagger
30ab42c3-ced3-443b-ac41-332ec3d1dc60 | Postman
2b6f204d-0338-41ca-a82a-5c3c759ff510 | Tools
43c5b3e0-7eb6-405b-9db2-7540fba679d5 | apis
8cef0a7e-63b4-4dbf-b942-1f8355c8ab45 | Data Science
86a8f01e-3390-41c7-a23a-7d603815ec02 | Design
6f45bbb4-f78c-4a81-9b50-210fe6c5ad27 | Ethics in CS
5519988f-bebd-46c3-9d9b-4e02642faddc | Code Reviews
2bf14dc6-a66c-4ff1-b75d-4d1051e1242a | Functional Programming
44929775-9bb4-4840-af64-c6b0649d6677 | Elm
bff25abb-9589-45db-8113-c762a3966690 | Math
bb5a617c-0a92-48c7-a786-de89b7ace93a | Automation
0ed56654-4752-4d35-aa8e-25ee1fcfd24e | Security

### LINKED ISSUE #35: Allow developers to use local SQLite file instead of PostgreSQL
Currently, Codebuddies README says it is necessary to install PostgreSQL in order to develop the project. This may prove as an unnecessary barrier to entry, particularly for the prototypal nature of the project in its current state. Until this project is more mature (and possibly deployed at some staging server), we should allow local development to proceed with a simple SQLite database.

## Task
- [ ] Create an optional environment variable approach to allow developers to use SQLite instead of PostgreSQL

### PR DESCRIPTION
**Pull request by brylie**
Closes #16 - use django-taggit for simple keyword tag management
Closes #25 - UUID maintenance for demo tags
Closes #35 - optional SQLite development

### CODE REVIEW

**Comment by brylie** [comment]
Ping @lpatmo @BethanyG

**Comment by lpatmo** [comment]
Thanks for this, @brylie! I like `django-taggit` a lot. Two comments:

- Let's remove the `optional SQLite development` bit in the settings file, please? #35 made sense, but I'm sorry for not making it clearer in [decision logs](https://github.com/codebuddies/django-concept/wiki/Decision-log) that I plan to deploy Postgres in production using https://blog.digitalocean.com/announcing-managed-databases-for-postgresql/. (That decision log is entirely new, btw, but I plan to keep it up to date)

- Do you want me to file a separate issue re: django-taggit support in DRF? It looks like we may need https://github.com/glemmaPaul/django-taggit-serializer too.

**Comment by brylie** [comment]
K, I removed optional SQLite support.

Yes, please open a follow-up task for DRF serializer(s).

**Comment by lpatmo** [comment]
Thank you @brylie! 

Looks like Bethany filed this issue last night, which encompasses the tasks related to supporting taggit in DRF: https://github.com/codebuddies/django-concept/issues/43

**Pull request merged**
